"""
auditor.py — LLM-Powered Smart Contract Audit Engine
Sends Solidity source + tool outputs to Claude for structured security analysis.
"""

import os
import json
import argparse
from pathlib import Path
from datetime import datetime, timezone

import anthropic

from llm_auditor.prompt_templates import build_audit_prompt, build_remediation_prompt


class LazyClient:
    _client = None
    @classmethod
    def get(cls):
        if cls._client is None:
            api_key = os.environ.get("ANTHROPIC_API_KEY")
            if not api_key:
                raise RuntimeError(
                    "ANTHROPIC_API_KEY not set. Export it or use --skip-llm."
                )
            cls._client = anthropic.Anthropic(api_key=api_key)
        return cls._client


AUDIT_MODEL = "claude-3-5-sonnet-20241022"


class SmartContractAuditor:
    def __init__(self, contract_path: str, static_results: dict = None, fuzz_results: dict = None):
        self.contract_path = Path(contract_path)
        self.contract_source = self.contract_path.read_text()
        self.contract_name = self.contract_path.stem
        self.static_results = static_results or {}
        self.fuzz_results = fuzz_results or {}
        self.audit_result = {}

    def run_full_audit(self) -> dict:
        print(f"[*] Starting LLM audit of {self.contract_name}...")

        print("[*] Phase 1: Vulnerability identification...")
        vuln_prompt = build_audit_prompt(
            contract_name=self.contract_name,
            source_code=self.contract_source,
            static_results=self.static_results,
            fuzz_results=self.fuzz_results,
        )

        vuln_response = LazyClient.get().messages.create(
            model=AUDIT_MODEL,
            max_tokens=4096,
            messages=[{"role": "user", "content": vuln_prompt}],
        )
        vuln_analysis = vuln_response.content[0].text

        print("[*] Phase 2: Generating remediation advice...")
        remediation_prompt = build_remediation_prompt(
            contract_name=self.contract_name,
            source_code=self.contract_source,
            vulnerability_analysis=vuln_analysis,
        )

        remediation_response = LazyClient.get().messages.create(
            model=AUDIT_MODEL,
            max_tokens=4096,
            messages=[{"role": "user", "content": remediation_prompt}],
        )
        remediation_analysis = remediation_response.content[0].text

        self.audit_result = {
            "contract_name": self.contract_name,
            "audit_timestamp": datetime.now(timezone.utc).isoformat(),
            "audited_by": "UMBA Consulting Engineers \u2014 AI Audit Engine",
            "vulnerability_analysis": vuln_analysis,
            "remediation_analysis": remediation_analysis,
            "model_used": AUDIT_MODEL,
            "source_lines": len(self.contract_source.splitlines()),
        }

        print(f"[\u2713] Audit complete for {self.contract_name}")
        return self.audit_result

    def save_json(self, output_path: str = None):
        if not output_path:
            output_path = f"reports/{self.contract_name}_audit.json"
        Path(output_path).parent.mkdir(parents=True, exist_ok=True)
        with open(output_path, "w") as f:
            json.dump(self.audit_result, f, indent=2)
        print(f"[\u2713] JSON report saved: {output_path}")

    def save_markdown(self, output_path: str = None):
        if not output_path:
            output_path = f"reports/{self.contract_name}_audit.md"
        Path(output_path).parent.mkdir(parents=True, exist_ok=True)

        md = (
            "# Smart Contract Audit Report\n\n"
            f"**Contract:** {self.audit_result.get('contract_name')}  \n"
            f"**Date:** {self.audit_result.get('audit_timestamp')}  \n"
            f"**Audited By:** {self.audit_result.get('audited_by')}  \n"
            f"**Source Lines:** {self.audit_result.get('source_lines')}\n\n"
            "---\n\n"
            "## Vulnerability Analysis\n\n"
            f"{self.audit_result.get('vulnerability_analysis', '')}\n\n"
            "---\n\n"
            "## Remediation Recommendations\n\n"
            f"{self.audit_result.get('remediation_analysis', '')}\n\n"
            "---\n\n"
            "*Generated by UMBA Smart Contract Formal Verification Suite*\n"
        )
        with open(output_path, "w") as f:
            f.write(md)
        print(f"[\u2713] Markdown report saved: {output_path}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="LLM Smart Contract Auditor")
    parser.add_argument("--contract", required=True, help="Path to .sol contract")
    parser.add_argument("--static", help="Path to Slither JSON output")
    parser.add_argument("--fuzz", help="Path to Echidna output")
    parser.add_argument("--output", help="Output report path")
    args = parser.parse_args()

    static = {}
    if args.static and Path(args.static).exists():
        with open(args.static) as f:
            static = json.load(f)

    fuzz = {}
    if args.fuzz and Path(args.fuzz).exists():
        with open(args.fuzz) as f:
            fuzz = json.load(f)

    auditor = SmartContractAuditor(
        contract_path=args.contract,
        static_results=static,
        fuzz_results=fuzz,
    )
    result = auditor.run_full_audit()
    auditor.save_json()
    auditor.save_markdown()

    print("\n" + "=" * 60)
    print("  AUDIT SUMMARY")
    print("=" * 60)
    text = result.get("vulnerability_analysis", "")
    print(text[:500] + ("..." if len(text) > 500 else ""))
